CREATE OR REPLACE TABLE YOURLIB.SALES (
    SALEDATE DATE,
    ITEMCD VARCHAR(10) CCSID 1208,
    ITEMNAME VARCHAR(50) CCSID 1208,
    QTY INT,
    PRICE INT,
    AMOUNT INT,
    CUSTOMER VARCHAR(50) CCSID 1208,
    REGION VARCHAR(20) CCSID 1208,
    STAFF VARCHAR(20) CCSID 1208
);

LABEL ON COLUMN YOURLIB.SALES (
    SALEDATE IS '日付',
    ITEMCD IS '商品コード',
    ITEMNAME IS '商品名',
    QTY IS '数量',
    PRICE IS '単価',
    AMOUNT IS '金額',
    CUSTOMER IS '顧客名',
    REGION IS '地域',
    STAFF IS '担当者'
);
